### ISSUE TITLE
Readme images storage

### ISSUE THREAD

**Issue by Brains** [Brains/Finances#1]
![1](https://cloud.githubusercontent.com/assets/5301844/11852649/e10a77a2-a441-11e5-90f5-ed2bc44ec2f3.png)
![2](https://cloud.githubusercontent.com/assets/5301844/11852650/e11124b2-a441-11e5-9ca0-2a9fe4668a4b.png)
![3](https://cloud.githubusercontent.com/assets/5301844/11852651/e12272c6-a441-11e5-8902-940df6fd7170.png)
![4](https://cloud.githubusercontent.com/assets/5301844/11852652/e122fe3a-a441-11e5-8178-4a7eb61c3676.png)
![5](https://cloud.githubusercontent.com/assets/5301844/11852653/e1250e32-a441-11e5-98c4-7956a0a38844.png)
![6](https://cloud.githubusercontent.com/assets/5301844/11893817/dd60128e-a57b-11e5-8078-0cb00e7ba676.png)

**Comment by CompleteBrains** [comment]
![tracker](https://cloud.githubusercontent.com/assets/5301844/12006754/480f7c20-abec-11e5-8e58-f73d67e1c521.gif)

**Comment by CompleteBrains** [comment]
![statistics](https://cloud.githubusercontent.com/assets/5301844/12006799/5a1edb2a-abee-11e5-8e47-4ee2a960eb48.gif)

**Comment by CompleteBrains** [comment]
![statistics](https://cloud.githubusercontent.com/assets/5301844/12006854/0f752d1a-abf1-11e5-878f-cb8e1f1e71db.gif)
![tracker](https://cloud.githubusercontent.com/assets/5301844/12006855/0f75c608-abf1-11e5-809d-d57797e33a60.gif)
